apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  replicas: {{ .Values.backend.replicaCount}}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-pod
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: app-config