apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-pod
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag}}"
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: app-config