apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS votes (
        animal_type VARCHAR(50) PRIMARY KEY,
        votes_count INTEGER DEFAULT 0
    );
    INSERT INTO votes VALUES ('cats', 0), ('dogs',  0), ('giraffes', 0) ON CONFLICT (animal_type) DO NOTHING;