apiVersion: v1
kind: Secret
metadata: 
  name: postgres-secret-example
  namespace: dev-environment
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: c3VwZXJwYXNzd29yZA==
  DB_NAME: dm90aW5nX2FwcA==
